title: Daniel Hearn
catchphrase: Student interested in the web
markdown: kramdown
blog: /blog.html
permalink: /blog/:title
github: https://github.com/DanielHearn
codepen: https://codepen.io/danhearn/
manytwich: http://danielhearn.co.uk/manytwitch
#repository: DanielHearn/danielhearn.github.io

collections:
  - projects

plugins_dir:
  - jekyll-sitemap
